config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  # root to: 'categories#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do

    member do
      post :vote
    end

    # resources :comments, only: [:create]
  	resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  # resources :users, only: [:create]
  resources :users, except: [:destroy]
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
	has_many :comments, dependent: :destroy
	has_many :post_categories
	has_many :categories, through: :post_categories
	has_many :votes, as: :voteable

	validates :title, presence: true, length: {minimum: 5}
	validates :url, 	presence: true, uniqueness: true
	validates :description, presence: true

	# before_save {|post| post.create_slug}
	before_save :create_slug

	def total_votes
		up_votes - down_votes
	end

	def up_votes
		self.votes.where(vote: true).size
	end

	def down_votes
		self.votes.where(vote: false).size
	end

	def to_param
		self.title_slug
	end

	def create_slug
		self.title_slug = self.title.gsub(" ","-").downcase
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, only: [:edit, :update, :create, :vote]

  def index
  	@posts = Post.all.sort_by {|e| e.total_votes}.reverse
  end

  def show
  	@comment = Comment.new
  end

  def edit
    # binding.pry
  end

  def update
  	# binding.pry

    # @post.categories = []
    # categories_param

    if @post.update(post_param)
      flash[:notice] = "update success"
      redirect_to post_path(@post)
    else
      # flash.now = "just test"
      render :edit
    end
  end


  def new
    @post = Post.new
  end

  def create
    # binding.pry
    @post = Post.new(post_param)
    @post.creator = current_user

    if @post.save
      # binding.pry
      flash[:notice] = "create new post"
      redirect_to posts_path
    else
      # binding.pry
      render :new
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote once."
        end

        redirect_to :back
      end
      format.js #預設vote.js.erb
    end
  end

  private

  def post_param
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(title_slug: params[:id])
    # binding.pry
  end

end

app/views/posts/_comment.html.erb
<% show_post ||= false%>

<div class='row'>
  <div class='span1 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post,comment, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
    <% end %>
    <span id='comment_<%=comment.id%>_votes'><%= comment.total_votes %> votes</span>
    <% if logged_in? %>
      <br/>
      <%= link_to vote_post_comment_path(comment.post,comment, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <p>
      "<%= comment.body %>"
      <% if show_post %>
        on <%= link_to comment.post.title, post_path(comment.post) %>
      <% end %>
    </p>
    <p>
      <span class='quiet'>by </span><%= comment.creator.username %>
      <small> at <%= comment.created_at %></small>
    </p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/error', obj:@post %>

<div class = 'well'>
	<%= form_for @post do |f| %>
		<div class = 'control-group'>
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class = 'control-group'>
			<%= f.label :url %>
			<%= f.text_field :url %>
		</div>
		<div class = 'control-group'>
			<%= f.label :description %>
			<%= f.text_area :description, rows: 5 %>
		</div>
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
			<% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
		<% end %>
		<p></p>
		<% if current_user %>
			<%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
		<% end %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class = 'row'>
	<div class='span1 well text-center'>
		<% if logged_in? %>
			<%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
				<i class='icon-arrow-up'></i>
			<% end %>
			<br/>
		<% end %>
		<span id='post_<%=post.id%>_votes'> <%= post.total_votes%> votes </span>
		<% if logged_in? %>
			<br/>
			<%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
				<i class='icon-arrow-down'></i>
			<% end %>
		<% end %>
	</div>
	<div class='span8 well'>
		<p>
			<% post.categories.each do |e| %>
				<%= link_to e.name, category_path(e), class: 'label' %>
			<% end %>
		</p>
		<h4><%= link_to post.title, fix_url(post.url) %></h4>
		<p><%= post.description %></p>
		<p>
			<span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
			<small>at <%= format_time(post.created_at) %></small>
		</p>
		<% if comment == nil %>
			<small>
				<span>
					<%= link_to("#{post.comments.size} comments", post_path(post)) %>

				</span>
			</small>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/title', title: 'Edit your post here!' %>

<%= render :partial => "form" %>

app/views/posts/index.html.erb
<%= render 'shared/title', title: 'All Posts' %>

<% @posts.sort_by{|p| p.created_at}.reverse.each do |p| %>
	<%= render 'post', post: p , comment: nil%>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/title', title: 'Create Post' %>
<%= render :partial => "form" %>

app/views/posts/show.html.erb
<p class='pull-right'>
  [<%= link_to 'Edit this post', edit_post_path(@post) %>]
</p>

<%= render 'shared/title', title: @post.title %>
<%= render 'post', post: @post, comment: @comment %>

<%= render 'shared/error', obj:@comment %>

<!-- <h5>Add Comment:</h5> -->
<!--
<%= form_tag post_comments_path(@post) do %>
	<%= text_area_tag :keyword %>
	<br>
	<%= submit_tag %>
<% end %>
-->

<% if current_user %>
  <%= form_for [@post, @comment] do |c| %>
  	<div class = 'control-group'>
  		<%= c.label :body, 'Leave a comment' %>
  		<%= c.text_area :body, rows: 3, class: 'span4' %>
  	</div>
  	<%= c.submit 'add new comment', class: 'btn btn-primary'%>
  <% end %>
<% end %>

<h5>Comments:</h5>

<% @post.comments.each do |c| %>
	<%= render 'comment', comment: c %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%=@post.id%>_votes").html("<%= @post.total_votes %> votes")
<% else %>
  alert("You can only vote once.")
<% end %>